use customer_shopping_behavior;
show tables;
select * from customer_shopping_behavior;

-- Rename of table name 
alter table customer_shopping_behavior rename customer;

select * from customer;

-- Rename columns name 
ALTER TABLE customer
RENAME COLUMN `purchase_amount_(usd)` TO purchase_amount;
-- Adding new columns age_group 
ALTER TABLE customer
ADD age_group VARCHAR(20); 

SET SQL_SAFE_UPDATES = 0;

UPDATE customer
SET age_group =
    CASE
        WHEN age <= 18 THEN 'Young'
        WHEN age BETWEEN 18 AND 35 THEN 'Adult'
        WHEN age BETWEEN 36 AND 60 THEN 'Middle Age'
        ELSE 'Senior'
    END;

-- Problem to solving

-- Q1. What is the total revenue generated by male vs. female customers? 
SELECT gender, SUM(purchase_amount) AS revenue
FROM 
customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
 from customer
 where discount_applied = 'Yes' and 
 purchase_amount >= (select avg(purchase_amount) from customer);
 
-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as Average_review from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type ,round(avg(purchase_amount),2) as average_purchase from customer
where shipping_type in ('Express','Standard')
group by shipping_type;

-- Q5. Do subscribed customer s spend more? Compare average spend and total revenue 
select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue 
from customer
group by subscription_status
order by total_revenue,average_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate 
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = '1' then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
    from customer
)
select customer_segment ,count(*) as "Number of customer"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with item_count as (
select 	category, item_purchased, count(customer_id) as total_order,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category, item_purchased, total_order from item_count 
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group ,sum(purchase_amount) as revenue from customer
group by age_group;
